# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [4knWnG, SG230294]
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://www.paypal.com/paypalme/dendibiden']
